import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/tailwind.scss'
import '@arco-design/web-react/dist/css/arco.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
